# -*- coding: utf-8 -*-
"""CrackDetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10cU9IJj4r619iuG9cj4vGp9CLaCUCvAS
"""

from google.colab import drive
import os

# Mount Google Drive
drive.mount('/content/drive')

# Paths
images_dir = "/content/drive/MyDrive/crack-detection/images"
annotations_dir = "/content/drive/MyDrive/crack-detection/annotations"

# Get filenames without extensions
image_files = {os.path.splitext(f)[0] for f in os.listdir(images_dir) if os.path.isfile(os.path.join(images_dir, f))}
annotation_files = {os.path.splitext(f)[0] for f in os.listdir(annotations_dir) if os.path.isfile(os.path.join(annotations_dir, f))}

# Images without annotations
missing_annotations = image_files - annotation_files
print(f"Number of images missing annotations: {len(missing_annotations)}")
if missing_annotations:
    print("Images missing annotations:")
    for img in sorted(missing_annotations):
        print(img)

# Annotations without images
missing_images = annotation_files - image_files
print(f"\nNumber of annotations missing images: {len(missing_images)}")
if missing_images:
    print("Annotations missing images:")
    for ann in sorted(missing_images):
        print(ann)

# xml_to_yolo.py
import os
import xml.etree.ElementTree as ET

# Paths (updated to Google Drive)
dataset_dir = '/content/drive/MyDrive/crack-detection'
annotations_dir = os.path.join(dataset_dir, 'annotations')
labels_dir = os.path.join(dataset_dir, 'labels')

os.makedirs(labels_dir, exist_ok=True)

# Define classes (adjust if more types of cracks exist)
classes = ["Longitudinal crack"]  # class index 0

def convert_bbox(size, box):
    dw = 1.0 / size[0]
    dh = 1.0 / size[1]
    x = (box[0] + box[1]) / 2.0 - 1
    y = (box[2] + box[3]) / 2.0 - 1
    w = box[1] - box[0]
    h = box[3] - box[2]
    x = x * dw
    w = w * dw
    y = y * dh
    h = h * dh
    return (x, y, w, h)

for xml_file in os.listdir(annotations_dir):
    if not xml_file.endswith('.xml'):
        continue
    in_file = os.path.join(annotations_dir, xml_file)
    tree = ET.parse(in_file)
    root = tree.getroot()

    size = root.find('size')
    w = int(size.find('width').text)
    h = int(size.find('height').text)

    out_file = os.path.join(labels_dir, os.path.splitext(xml_file)[0] + '.txt')
    with open(out_file, 'w') as f:
        for obj in root.iter('object'):
            cls = obj.find('name').text
            if cls not in classes:
                continue
            cls_id = classes.index(cls)
            xmlbox = obj.find('bndbox')
            b = (
                int(xmlbox.find('xmin').text),
                int(xmlbox.find('xmax').text),
                int(xmlbox.find('ymin').text),
                int(xmlbox.find('ymax').text)
            )
            bb = convert_bbox((w, h), b)
            f.write(f"{cls_id} {' '.join([str(a) for a in bb])}\n")

print("Conversion completed. Labels saved in:", labels_dir)

from google.colab import drive
import os

# Mount Google Drive
drive.mount('/content/drive')

# Paths to your folders in Google Drive
images_dir = '/content/drive/MyDrive/crack-detection/images'
annotations_dir = '/content/drive/MyDrive/crack-detection/annotations'
labels_dir = '/content/drive/MyDrive/crack-detection/labels'

# Function to count files in a directory
def count_files(directory):
    return len([f for f in os.listdir(directory) if os.path.isfile(os.path.join(directory, f))])

# Count files
print(f"Number of image files: {count_files(images_dir)}")
print(f"Number of annotation files: {count_files(annotations_dir)}")
print(f"Number of label files: {count_files(labels_dir)}")

import os

labels_dir = "/content/drive/MyDrive/crack-detection/labels"

removed_count = 0

for filename in os.listdir(labels_dir):
    if filename.endswith(".txt"):
        file_path = os.path.join(labels_dir, filename)

        # Check if file is empty (0 bytes)
        if os.path.getsize(file_path) == 0:
            os.remove(file_path)
            removed_count += 1
            print(f"Deleted EMPTY label: {filename}")
            continue

        # Check if file contains only whitespace or blank lines
        with open(file_path, "r") as f:
            content = f.read().strip()

        if content == "":
            os.remove(file_path)
            removed_count += 1
            print(f"Deleted BLANK label: {filename}")

print(f"\nTotal empty labels removed: {removed_count}")

import os

# Paths
images_dir = "/content/drive/MyDrive/crack-detection/images"
xml_dir = "/content/drive/MyDrive/crack-detection/annotations"
txt_dir = "/content/drive/MyDrive/crack-detection/labels"

# Collect existing TXT label names (without extension)
txt_files = {os.path.splitext(f)[0] for f in os.listdir(txt_dir)}

deleted_images = 0
deleted_xml = 0

# Check every image in the dataset
for img_file in os.listdir(images_dir):
    if img_file.lower().endswith((".jpg", ".jpeg", ".png")):

        img_name = os.path.splitext(img_file)[0]

        # If image has NO corresponding TXT → delete image + XML
        if img_name not in txt_files:
            img_path = os.path.join(images_dir, img_file)
            xml_path = os.path.join(xml_dir, img_name + ".xml")

            # Delete image
            if os.path.exists(img_path):
                os.remove(img_path)
                deleted_images += 1
                print("Deleted image:", img_file)

            # Delete XML (if exists)
            if os.path.exists(xml_path):
                os.remove(xml_path)
                deleted_xml += 1
                print("Deleted XML:", img_name + ".xml")

print("\nSummary:")
print("Images deleted:", deleted_images)
print("XML files deleted:", deleted_xml)

# split_dataset_safe.py
import os
import random
import shutil

# Paths (Google Drive)
dataset_dir = '/content/drive/MyDrive/crack-detection'
images_dir = os.path.join(dataset_dir, 'images')
annotations_dir = os.path.join(dataset_dir, 'annotations')
labels_dir = os.path.join(dataset_dir, 'labels')

# Train/val split ratio
split_ratio = 0.8  # 80% train, 20% val

# Check that folders exist
for path in [images_dir, annotations_dir, labels_dir]:
    if not os.path.exists(path):
        raise FileNotFoundError(f"Folder not found: {path}")

# List all image files (case-insensitive)
image_files = [f for f in os.listdir(images_dir) if f.lower().endswith(('.jpg', '.jpeg', '.png'))]
print(f"Total images found: {len(image_files)}")
print("First 10 images:", image_files[:10])

if len(image_files) == 0:
    raise ValueError("No image files found in the images directory!")

# Shuffle and split
random.shuffle(image_files)
split_index = int(len(image_files) * split_ratio)
train_files = image_files[:split_index]
val_files = image_files[split_index:]

# Create train/val folder structure
for subset in ['train', 'val']:
    for folder_type in ['images', 'annotations', 'labels']:
        os.makedirs(os.path.join(dataset_dir, subset, folder_type), exist_ok=True)

# Function to copy files safely
def copy_files(file_list, subset):
    for file_name in file_list:
        # Copy image
        src_image = os.path.join(images_dir, file_name)
        dst_image = os.path.join(dataset_dir, subset, 'images', file_name)
        shutil.copy2(src_image, dst_image)

        # Copy corresponding annotation (.xml)
        xml_file = os.path.splitext(file_name)[0] + '.xml'
        xml_src = os.path.join(annotations_dir, xml_file)
        xml_dst = os.path.join(dataset_dir, subset, 'annotations', xml_file)
        if os.path.exists(xml_src):
            shutil.copy2(xml_src, xml_dst)
        else:
            print(f"Warning: Annotation not found for {file_name}")

        # Copy corresponding label (.txt)
        txt_file = os.path.splitext(file_name)[0] + '.txt'
        txt_src = os.path.join(labels_dir, txt_file)
        txt_dst = os.path.join(dataset_dir, subset, 'labels', txt_file)
        if os.path.exists(txt_src):
            shutil.copy2(txt_src, txt_dst)
        else:
            print(f"Warning: Label not found for {file_name}")

# Copy files to train/val
print("\nCopying training files...")
copy_files(train_files, 'train')

print("\nCopying validation files...")
copy_files(val_files, 'val')

print("\nDataset split completed!")
print(f"Train: {len(train_files)} images")
print(f"Val: {len(val_files)} images")

# Optional: Verify counts in folders
for subset in ['train', 'val']:
    imgs = len(os.listdir(os.path.join(dataset_dir, subset, 'images')))
    anns = len(os.listdir(os.path.join(dataset_dir, subset, 'annotations')))
    lbls = len(os.listdir(os.path.join(dataset_dir, subset, 'labels')))
    print(f"{subset} folder counts -> Images: {imgs}, Annotations: {anns}, Labels: {lbls}")

from google.colab import drive
import os

# Mount Google Drive
drive.mount('/content/drive')

# Paths to your folders in Google Drive
images_dir = '/content/drive/MyDrive/crack-detection/val/images'
annotations_dir = '/content/drive/MyDrive/crack-detection/val/annotations'
labels_dir = '/content/drive/MyDrive/crack-detection/val/labels'

# Function to count files in a directory
def count_files(directory):
    return len([f for f in os.listdir(directory) if os.path.isfile(os.path.join(directory, f))])

# Count files
print(f"Number of image files: {count_files(images_dir)}")
print(f"Number of annotation files: {count_files(annotations_dir)}")
print(f"Number of label files: {count_files(labels_dir)}")

with open("/content/drive/MyDrive/crack-detection/data.yaml", "w") as f:
    f.write("""
train: /content/drive/MyDrive/crack-detection/train/images
val: /content/drive/MyDrive/crack-detection/val/images
nc: 1
names: ["Longitudinal crack"]
""")

!pip install ultralytics --upgrade

!pip install opencv-python-headless

from ultralytics import YOLO

# Load YOLOv8 small model pretrained on COCO
model = YOLO('yolov8s.pt')

# Train the model
model.train(
    data='/content/drive/MyDrive/crack-detection/data.yaml',  # YAML config
    epochs=50,      # Number of training epochs
    imgsz=512,      # Resize images to 512x512 for training
    batch=8,        # Batch size
    project='/content/drive/MyDrive/crack-detection/crack_detection',  # Save results in Drive
    name='yolov8_crack',
    exist_ok=True
)